import re

from pydantic import BaseModel, Field, field_validator

_FENCE_RE = re.compile(r"^\s*```[A-Za-z0-9_+-]*[ \t]*\n?|\n?[ \t]*```\s*$")


def clean_code_fix(value: str) -> str:
    """Strip markdown code fences / inline backticks an LLM may wrap code in.

    Internal newlines and leading indentation are preserved so multi-line
    fixes (e.g. a documentation header block) survive intact.
    """
    if value is None:
        return ""
    text = _FENCE_RE.sub("", str(value))
    stripped = text.strip()
    if "\n" not in stripped and len(stripped) >= 2 and stripped[0] == stripped[-1] == "`":
        text = stripped.strip("`")
    return text.rstrip()


class ComplianceFinding(BaseModel):
    """
    Structured representation of a compliance finding in R code.

    ``rule_id``, ``line_number`` and ``severity`` are deterministic metadata
    inherited from the CodeAnalyzer flag; the remaining fields may be
    generated by the LLM reviewer.
    """
    rule_id: str = Field(
        ..., 
        description="Identifier of the applicable synthetic rule"
    )
    line_number: int = Field(
        ...,
        description="1-based line number in the R script where the issue was flagged",
        ge=1
    )
    severity: str = Field(
        ..., 
        description="Potential severity of the finding"
    )
    finding: str = Field(
        ..., 
        description="Description of the identified issue"
    )
    evidence: str = Field(
        ..., 
        description="Relevant evidence from the R source code"
    )
    recommendation: str = Field(
        ..., 
        description="Suggested remediation"
    )
    confidence: float = Field(
        ..., 
        description="Model confidence in the finding",
        ge=0.0, 
        le=1.0
    )
    suggested_fix: str = Field(
        default="",
        description=(
            "Exact R code that replaces the non-compliant line (empty when no "
            "automated fix is available)"
        ),
    )

    @field_validator("suggested_fix", mode="before")
    @classmethod
    def _strip_fences(cls, value: str) -> str:
        return clean_code_fix(value)


class LLMReview(BaseModel):
    """
    The subset of a ComplianceFinding that the LLM is allowed to generate.

    Deterministic metadata (rule_id, line_number, severity) is deliberately
    excluded so the model cannot alter it; the agent merges it back in.
    """
    finding: str = Field(
        ...,
        description="Concise, factual explanation of why the snippet violates the rule"
    )
    evidence: str = Field(
        ...,
        description="Exact quote of the offending R code from the snippet"
    )
    recommendation: str = Field(
        ...,
        description="Concrete remediation consistent with the rule's recommendation"
    )
    confidence: float = Field(
        ...,
        description="How clearly the snippet violates the rule, from 0.0 to 1.0",
        ge=0.0,
        le=1.0
    )
    suggested_fix: str = Field(
        ...,
        description=(
            "The exact corrected R code that replaces the flagged line. Raw code "
            "only: no markdown backticks, no explanation, no line numbers."
        ),
    )

    @field_validator("suggested_fix", mode="before")
    @classmethod
    def _strip_fences(cls, value: str) -> str:
        return clean_code_fix(value)
