from pydantic import BaseModel, Field

class ComplianceFinding(BaseModel):
    """
    Structured representation of a compliance finding in R code.

    ``rule_id``, ``line_number`` and ``severity`` are deterministic metadata
    inherited from the CodeAnalyzer flag; the remaining fields may be
    generated by the LLM reviewer.
    """
    rule_id: str = Field(
        ..., 
        description="Identifier of the applicable synthetic rule"
    )
    line_number: int = Field(
        ...,
        description="1-based line number in the R script where the issue was flagged",
        ge=1
    )
    severity: str = Field(
        ..., 
        description="Potential severity of the finding"
    )
    finding: str = Field(
        ..., 
        description="Description of the identified issue"
    )
    evidence: str = Field(
        ..., 
        description="Relevant evidence from the R source code"
    )
    recommendation: str = Field(
        ..., 
        description="Suggested remediation"
    )
    confidence: float = Field(
        ..., 
        description="Model confidence in the finding",
        ge=0.0, 
        le=1.0
    )


class LLMReview(BaseModel):
    """
    The subset of a ComplianceFinding that the LLM is allowed to generate.

    Deterministic metadata (rule_id, line_number, severity) is deliberately
    excluded so the model cannot alter it; the agent merges it back in.
    """
    finding: str = Field(
        ...,
        description="Concise, factual explanation of why the snippet violates the rule"
    )
    evidence: str = Field(
        ...,
        description="Exact quote of the offending R code from the snippet"
    )
    recommendation: str = Field(
        ...,
        description="Concrete remediation consistent with the rule's recommendation"
    )
    confidence: float = Field(
        ...,
        description="How clearly the snippet violates the rule, from 0.0 to 1.0",
        ge=0.0,
        le=1.0
    )
